### ISSUE TITLE
Objective Placeholder doesn't refresh on new entries

### ISSUE THREAD

**Issue by Edrow-6** [EvModder/EvStats#1]
Hi, the Objectives placeholders does't refresh on new scoreboard entry. I need to manualy reload placeholderAPI to display the new entry. It is possible to auto refresh the placeholder on new score entry ?

**Comment by EvModder** [comment]
Hmm, not quite sure from your description -- can you give the steps to recreate the issue? (and what it should be showing + what it actually displays)
